#define FIRST_LED 11
#define SECOND_LED 12
#define THIRD_LED 13
#define NO_OF_STATES 3
#define FIRST_STATE 1
#define DISPLAY_A 3
#define DISPLAY_B 2
#define DISPLAY_C 7
#define DISPLAY_D 8
#define DISPLAY_E 9
#define DISPLAY_F 4
#define DISPLAY_G 5
#define DISPLAY_DP 6
